name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: RafaelApolinario90
          outputs: |
            dist/github-snake.svg?color_snake=%230086ff&color_dots=#ebedf0,#9fc5ff,#6fb0ff,#3b92ff,#0a78ff
            dist/github-snake-dark.svg?palette=github-dark&color_snake=%230086ff&color_dots=#161b22,#0d2a4d,#0b3a78,#0850b3,#0566e6

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
